export const throwException = (err = new Error()) => { throw err }